backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Subheading, name: subheading, widget: string}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}


  - name: "publications"
    label: "Publications"
    folder: "src/pages/publications"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Authors", name: "authors", widget: string}
      - label: "Citation"
        name: "citation"
        widget: "object"
        fields:
          - {label: "MLA", name: "mla", widget: "markdown", default: "mla", required: false}
          - {label: "APA", name: "apa", widget: "markdown", default: "apa", required: false}
          - {label: "ISO690", name: "iso690", widget: "markdown", default: "iso690", required: false}
      - {label: "Source", name: "source", widget: "string", required: false}
      - {label: "Researchgate", name: "researchgate", widget: "string", required: false}
      - {label: "Preregistration", name: "preregistration", widget: "string",required: false}
      - {label: "PDF", name: "pdf", widget: "file", required: false}
      - {label: "Data", name: "data", widget: "file", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Abstrakt", name: "abstrakt", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list",  default: ["publication"]}

  - name: "team"
    label: "Team"
    folder: "src/pages/team"
    create: true
    slug: "member"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-post"}
      - {label: "Title", name: "title", widget: "string", default: "Team member"}
      - {label: "Image", name: image, widget: image}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "RG", name: "rg", widget: "string", default: "Reaserch gate", required: false}
      - {label: "GS", name: "gs", widget: "string", default: "google scholar", required: false}
      - {label: "Link", name: "link", widget: "string", default: "profile link", required: false}
      - {label: "Link", name: "link", widget: "string", default: "profile link", required: false}

  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "news"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-post"}
      - {label: "Title", name: "title", widget: "string", default: "News title"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: image, widget: image, required: false}
      - {label: "Content", name: "content", widget: "markdown"}

  - name: "resources"
    label: "Resources"
    folder: "src/pages/resources"
    create: true
    slug: "resources"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resources-page"}
      - {label: Title, name: title, widget: string, default: "Resources title"}
      - label: "Link-group"
        name: "Link-group"
        widget: "list"
        fields:
          - {label: Link label, name: link label, widget: string, default: "Resources title"}
          - {label: Link, name: link, widget: string, default: "Resources link"}

          
